name: Build Shared Libraries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2.0.2
        with:
          cmake-version: '3.10.x'

      - name: Set up Build Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake configuration
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: build

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2.0.2
        with:
          cmake-version: '3.10.x'

      - name: Create build directory
        run: mkdir -p build

      - name: Run CMake configuration
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: build

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2.0.2
        with:
          cmake-version: '3.10.x'

      - name: Create build directory
        run: mkdir build

      - name: Run CMake configuration
        run: cmake -G "Visual Studio 16 2019" -A x64 -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build